version: '6'
services:
  database-sqlserver:
    image: mcr.microsoft.com/mssql/server:2019-latest
    restart: always
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=Abc1234!@
      - MSSQL_PID=Developer
    ports:
      - '1433:1433'  # Cổng mặc định của SQL Server
    # expose:
    #   - 1433

  backend:
    build:
      context: ./api
      dockerfile: Dockerfile
    restart: unless-stopped
    environment:
      # - SQL_PORT=1433  # Cổng của SQL Server
      # - SQL_SERVER=database-sqlserver  # Tên dịch vụ SQL Server
      - SQL_SERVER=host.docker.internal
    ports:
      - 3000:3000
